export const teamData = {
  faculty: [
    {
      role: "SLC Principal",
      name: "Prof. Rabi Narayan Kar",
      image: "/assets/teams/principle.jpg",
      linkedin: "https://linkedin.com/in/prof-rabi",
      instagram: "https://instagram.com/prof_rabi",
      whatsapp: "+911234567890",
    },
    {
      role: "Convener",
      name: "Dr. Saubhagyalaxmi Singh",
      department: "convener",
      image: "/assets/teams/convener.jpg",
      whatsapp: "+911234567891",
      members: [
        {
          name: "Dr. Monika Goyal",
          role: "Dept. of Physics",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Mr. Balram Kindra",
          role: "Dept. of Mathematics",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Dr. Sushil Kumar",
          role: "Dept. of Computer Science",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Dr. Neha Bothra",
          role: "Dept. of Commerce",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Dr. Sunny Aggrawal",
          role: "Dept. of Physics",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Dr. Pranav Dass",
          role: "Dept. of Computer Science",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Dr. Leena Singh",
          role: "Dept. of Computer Science",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Dr. Kanika Solanki",
          role: "Dept. of Chemistry",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Dr. Nidhi Jain",
          role: "Dept. of Commerce",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Dr. Bisla Devi",
          role: "Dept. of Economics",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Ms. Priyanka Yadav",
          role: "Dept. of Commerce",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Dr. Rahul Boadh",
          role: "Dept. of Mathematics",
          image: "/assets/teams/user.webp",
        },
      ],
    },
  ],
  students: [
    {
      role: "President",
      name: "Abhishek kumar",
      image: "/assets/teams/IMG_9675.JPG",
      linkedin: "https://www.linkedin.com/in/abhishek-kumar-3349832b1/",
      instagram: "https://www.instagram.com/abhi__verse/",
      whatsapp: "+918527972684",
    },
    {
      role: "President",
      name: "Chaitanya Lohani",
      image: "/assets/teams/president2.jpg",
      linkedin: "https://www.linkedin.com/in/chaitanya-lohani",
      whatsapp: "+918287666486",
    },
    {
      role: "Outreach Coordinator",
      name: "Pooja Jha",
      image: "/assets/teams/coordinator.jpg",
      linkedin: "https://www.linkedin.com/in/pooja-jha-145a10289?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      instagram: "https://www.instagram.com/poojajha_441/",
      whatsapp: "+918287590453",
    },
    {
      role: "Innovation Activity Coordinator",
      name: "Harshita",
      image: "/assets/teams/cord_2.jpg",
      linkedin: "https://www.linkedin.com/in/harshita-bhardwaj-0462132b2?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      instagram: "https://www.instagram.com/harshubhardwaj17/",
      whatsapp: "+919211146715",
    },
    {
      role: "Secretary",
      name: "Gautam Sharma",
      image: "/assets/teams/cord_2.jpg",
      linkedin: "https://www.linkedin.com/in/harshita-bhardwaj-0462132b2?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      instagram: "https://www.instagram.com/harshubhardwaj17/",
      whatsapp: "+919211146715",
    },
    {
      role: "Treasurer",
      name: "Mukul Yadav",
      image: "/assets/teams/cord_2.jpg",
      linkedin: "https://www.linkedin.com/in/harshita-bhardwaj-0462132b2?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      instagram: "https://www.instagram.com/harshubhardwaj17/",
      whatsapp: "+919211146715",
    },
    {
      role: "Marketing And PR Head",
      name: "Jarul Gupta",
      department: "marketing",
      image: "/assets/teams/pr.jpg",
      whatsapp: "+911234567895",
      members: [
        {
          name: "Sareya Gupta",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Rounak Agrawal",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Piyush Bhaskar",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Palak Sharma",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Mohd Yausuf",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Radhe Nandan",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Pradhumn Gupta",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Hitesh Khatri",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Neeraj Tiwari",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Aryan Malhotra",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Disha Sharma",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Daksh Goyal",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Abdul Rehman Khan",
          role: "Marketing & PR",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
      ],
    },

    {
      role: "Content Head",
      name: "Khushal Gupta",
      department: "content",
      image: "/assets/teams/content.png",
      linkedin: "https://www.linkedin.com/in/khushalgupta/",
      instagram: "https://www.instagram.com/khushalgupta__/",
      whatsapp: "+911234567896",
      members: [
        {
          name: "Aishani",
          role: "Content Writing",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Hritik Sharma",
          role: "Content Writing",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Mukul Yadav",
          role: "Content Writing",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
      ],
    },
    {
      role: "Event Management Head",
      name: "Anshraj Singh",
      department: "event-management",
      image: "/assets/teams/management.jpg",
      instagram: "https://www.instagram.com/rajputanshhh/",
      whatsapp: "+911234567897",
      members: [
        {
          name: "Abhash Srivastava",
          role: "Event Management",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Vivek Kumar",
          role: "Event Management",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Harsh Kumar",
          role: "Event Management",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Krishna Yadav",
          role: "Event Management",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Dolly Seth",
          role: "Event Management",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Gourav Nigam",
          role: "Event Management",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Shivani Jha",
          role: "Event Management",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
      ],
    },
    {
      role: "Graphic's and Design Head",
      name: "Abhishek Kumar",
      department: "graphics",
      image: "/assets/teams/graphics.jpg",
      linkedin: "https://www.linkedin.com/in/abhishek-kumar-3349832b1/",
      instagram: "https://www.instagram.com/abhi__verse/",
      whatsapp: "+911234567898",
      members: [
        {
          name: "Disha Singh",
          role: "Graphics",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Pooja Jha",
          role: "Graphics",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
      ],
    },
    {
      role: "Technical Head",
      name: "Rahul Sharma",
      department: "technical",
      image: "/assets/teams/tech1.png",
      linkedin: "https://www.linkedin.com/in/rahul-sharma-14b096213/",
      instagram: "https://www.instagram.com/rahul09_30/",
      whatsapp: "+911234567899",
      members: [
        {
          name: "Shiwang Raj",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Gautam Sharma",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Sushil Singh",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Harshita Bhardwaj",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Sagar Gouda",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Alok",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
      ],
    },
    {
      role: "Technical Head",
      name: "Chaitanya Lohani",
      department: "technical_2",
      image: "/assets/teams/tech2.png",
      linkedin: "https://www.linkedin.com/in/chaitanya-lohani/",
      whatsapp: "+911234567800",
      members: [
        {
          name: "Shiwang Raj",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Gautam Sharma",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Sushil Singh",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Harshita Bhardwaj",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Sagar Gouda",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
        {
          name: "Alok",
          role: "Technical Team",
          linkedin: "https://linkedin.com/in/amit",
          instagram: "https://instagram.com/amit",
          whatsapp: "+911234567898",
          image: "/assets/teams/user.webp",
        },
      ],
    },
  ],
};
